language: java
jdk: openjdk8

# git strips the wrapper jar file so we have to force its download during the build
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# Improve Build Speed https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
    - $HOME/.m2

# Notifications https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
      dina.latypova23@gmail.com
    on_success: always # default: change
    on_failure: always # default: always


